# Generated by Django 4.1.6 on 2023-04-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='added',
        ),
    ]
